### ISSUE TITLE
Equivalent of RegExp.matchAll

### ISSUE THREAD

**Issue by danflomin** [le0pard/re2js#9]
Hey :) How are you?

I'm going over the library and its documentation, and I can't find an equivalent to JS's native `matchAll` function as found in [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll).

Is there an option to get all matches?
If not, is it possible to add this to the library?

Kind regards
Dan

**Comment by le0pard** [comment]
https://github.com/le0pard/re2js?tab=readme-ov-file#finding-matches - section called "Finding Matches"
